### ISSUE TITLE
Server Crash 1.16.5

### ISSUE THREAD

**Issue by rafaelkai** [AHilyard/Highlighter#1]
https://pastebin.com/yk0u7jvF

**Comment by AHilyard** [comment]
This is a client-side mod.  It appears you are running it on a dedicated server.

**Comment by rafaelkai** [comment]
That's what I thought at first, but when I enter my server with Highliter only in client it doesn't appear to work at all (it does work on singleplayer worlds though)

**Comment by AHilyard** [comment]
Interesting, I will look into this.  Sorry for the inconvenience.

**Comment by AHilyard** [comment]
This has been resolved in the latest release. (1.1.0)
