### ISSUE TITLE
Items getting coloured 

### ISSUE THREAD

**Issue by sternschnaube** [AHilyard/Highlighter#10]
![image](https://user-images.githubusercontent.com/120551916/233684572-706442dd-c663-4e3d-9bcc-fd33ef42163c.png)
![image](https://user-images.githubusercontent.com/120551916/233684677-e665bc2d-7fe1-4645-9e4d-e3ad61d0322d.png)
![image](https://user-images.githubusercontent.com/120551916/233684715-037c80ad-9123-413a-85f8-500e416ad994.png)

Item Borders config:
		# If the hotbar should display item borders.
		hotbar = true
		# If item borders should show for common items.
		show_for_common = false
		# If the borders should have square corners.
		square_corners = true
		# If the borders should fully envelop item slots (otherwise they will only show on the bottom portion of the slot).
		full_border = true
		# If the borders draw over items instead of under.
		over_items = false
		# If the borders should have a more prominent glow.
		extra_glow = false
		# If automatic borders (based on item rarity) should be enabled.
		auto_borders = true
		# If enabled and Legendary Tooltips is installed, borders will sync with tooltip border colors.
		legendary_tooltips_sync = true

Highlighter config:
		# If new item markers should be cleared when the inventory is closed.
		clear_on_close = true
		# If new item markers should be cleared when the item tooltip is displayed.
		clear_on_hover = false
		# If icons should match the color of items names (as shown in tooltips).  Otherwise icons will all be gold.
		item_name_color = true
		# If new item markers should show on the hotbar.
		show_on_hotbar = true

It seems that the items getting the Item name colour.
Fabric 1.19.4 / Loader 0.14.19
Iceberg 1.1.9
Prism 1.0.4
Item Borders 1.2.0
Highlighter 1.1.5

**Comment by AHilyard** [comment]
Thank you for the report!  I've fixed this issue in version 1.1.6.
