### ISSUE TITLE
Crashing at 1.19 forge

### ISSUE THREAD

**Issue by erwavvy** [AHilyard/Highlighter#4]
I'm getting this while trying to run my minecraft, exists any fix or maybe 1.19 bug?
![Screenshot_1](https://user-images.githubusercontent.com/109924358/180666865-ff6e103b-2d58-4530-8d33-c1dbb23ac75e.png)

The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.EntityItemPickupEvent.getPlayer()'
Código de error: -1

**Comment by AHilyard** [comment]
Thank you for the report, this has now been fixed in version 1.1.4. (Supports both 1.19 and 1.19.1)
Enjoy! 😄
