### ISSUE TITLE
[Request] Highlight items also in backpack

### ISSUE THREAD

**Issue by jbrandek** [AHilyard/Highlighter#6]
Hi, really helpful mod thanks for creating it, do you think it would be possible to add compatibility with backpack?
Im using sophisticated backpack and if it goes straight to backpack it does not highlight the new item

Thanks

**Comment by AHilyard** [comment]
Hi there, glad you like the mod!  Unfortunately, I won't be able to add support for Sophisticated Backpacks from my side because of the way that mod was coded.  Sorry about that.
